const pets = [
{
    id: 1,
    name: "Luna",
    species: "Dog",
    breed: "Golden Retriever",
    age: "2 Years",
    location: "Kochi, Kerala",
    owner: "Adarsh Nair",
    phone: "919847012345",
    size: "Large",
    activity: "High",
    hypoallergenic: false,
    requiresYard: true,
    cost: "₹15,000",
    food: "Chicken & Rice, Pedigree",
    description: "A bundle of joy who loves beach walks at Fort Kochi.",
    image: "https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=600"
},

{
    id: 2,
    name: "Milo",
    species: "Cat",
    breed: "Tabby",
    age: "4 Years",
    location: "Trivandrum, Kerala",
    owner: "Meera Krishnan",
    phone: "919446054321",
    size: "Small",
    activity: "Low",
    hypoallergenic: false,
    requiresYard: false,
    cost: "₹2,000",
    food: "Whiskas, Fresh Sardines",
    description: "Professional napper and expert lap warmer from the capital.",
    image: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&q=80&w=600"
},

{
    id: 3,
    name: "Oliver",
    species: "Rabbit",
    breed: "Lop Ear",
    age: "1 Year",
    location: "Kozhikode, Kerala",
    owner: "Rahul Das",
    phone: "919745098765",
    size: "Small",
    activity: "Medium",
    hypoallergenic: true,
    requiresYard: false,
    cost: "₹1,500",
    food: "Timothy Hay, Spinach",
    description: "Very gentle and loves the cool breeze of Malabar.",
    image: "https://images.pexels.com/photos/4001296/pexels-photo-4001296.jpeg?auto=compress&cs=tinysrgb&w=600"
},

{
    id: 4,
    name: "Pip",
    species: "Bird",
    breed: "Parakeet",
    age: "6 Months",
    location: "Thrissur, Kerala",
    owner: "Sreejith Varma",
    phone: "919048011223",
    size: "Small",
    activity: "Medium",
    hypoallergenic: true,
    requiresYard: false,
    cost: "₹800",
    food: "Millet, Guava slices",
    description: "A social butterfly who loves the festival sounds of Thrissur.",
    image: "https://senecaparkzoo.org/wp-content/uploads/2023/04/Indian-Ring-neck-Parakeet-IMG_9280-2-768x768.jpg"
},

{
    id: 5,
    name: "Shelly",
    species: "Hen",
    breed: "Slider",
    age: "10 Years",
    location: "Alappuzha, Kerala",
    owner: "Ancy Joseph",
    phone: "919633044556",
    size: "Small",
    activity: "Low",
    hypoallergenic: true,
    requiresYard: false,
    cost: "₹500",
    food: "Grain mix, Veggie scraps",
    description: "Quiet, observant, and loves life near the backwaters.",
    image: "https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?auto=format&fit=crop&q=80&w=600"
},

{
    id: 6,
    name: "Barnaby",
    species: "Turtle",
    breed: "Giant Cavy",
    age: "3 Years",
    location: "Munnar, Kerala",
    owner: "Abhijit Pillai",
    phone: "919947077889",
    size: "Large",
    activity: "Low",
    hypoallergenic: false,
    requiresYard: true,
    cost: "₹12,000",
    food: "Aquatic plants, Lettuce",
    description: "The chillest companion. Thrives in the Munnar mist!",
    image: "https://opb-opb-prod.cdn.arcpublishing.com/resizer/v2/QITEYZ22ABMF3CEKJLKRAGUJEM.jpg"
},

{
    id: 7,
    name: "Cheddar",
    species: "Hamster",
    breed: "Syrian",
    age: "1 Year",
    location: "Kottayam, Kerala",
    owner: "Kevin Thomas",
    phone: "919562033445",
    size: "Small",
    activity: "High",
    hypoallergenic: true,
    requiresYard: false,
    cost: "₹1,200",
    food: "Hamster seeds, Apple bits",
    description: "Small but full of energy, loves hiding in rice husks.",
    image: "https://images.unsplash.com/photo-1425082661705-1834bfd09dca?auto=format&fit=crop&q=80&w=600"
},

{
    id: 8,
    name: "Finn",
    species: "Fish",
    breed: "Betta",
    age: "2 Years",
    location: "Palakkad, Kerala",
    owner: "Rishi Menon",
    phone: "919188066778",
    size: "Small",
    activity: "Low",
    hypoallergenic: true,
    requiresYard: false,
    cost: "₹450",
    food: "Betta pellets, Bloodworms",
    description: "Stunning colors, peaceful to watch during Palakkad sunsets.",
    image: "https://freshwateraquatica.org/cdn/shop/products/Screenshot_78_450x450.png?v=1693570790"
},

{
    id: 9,
    name: "Bella",
    species: "Dog",
    breed: "Poodle",
    age: "5 Years",
    location: "Wayanad, Kerala",
    owner: "Laya George",
    phone: "919387022334",
    size: "Medium",
    activity: "Medium",
    hypoallergenic: true,
    requiresYard: true,
    cost: "₹25,000",
    food: "Royal Canin, Boiled Egg",
    description: "Highly intelligent and perfect for Wayanad nature lovers.",
    image: "https://image.petmd.com/files/styles/978x550/public/2023-01/toy-poodle.jpg"
},

{
    id: 10,
    name: "Jasper",
    species: "Cat",
    breed: "Bengal Cat",
    age: "3 Years",
    location: "Malappuram, Kerala",
    owner: "Faisal Khan",
    phone: "919207055667",
    size: "Medium",
    activity: "High",
    hypoallergenic: false,
    requiresYard: false,
    cost: "₹30,000",
    food: "Raw Tuna, High-protein dry food",
    description: "Active, vocal, and fast like a little leopard.",
    image: "https://www.trupanion.com/images/trupanionwebsitelibraries/bg/bengal-cat.jpg"
}
];

function getPets() {
    return pets;
}